### ISSUE TITLE
TDD 2025 tasks

### ISSUE THREAD

**Issue by hadley** [tidyverse/tidy-dev-day#54]
So we remember all the tasks that we assigned to folks and can repeat in future years:

## Four months before (May)

* [x] Find a location — @lionel- 
* [x] Create [event page](https://lu.ma/mpr5c30q) page — @hadley 
* [x] Write intro the blog post — @topepo. https://github.com/tidyverse/tidyverse.org/pull/742
* [x] Commission token of appreciation — @hadley 
* [x] Schedule Git workshops — @mine-cetinkaya-rundel (8/19, 11am-12pm)
* [x] Find and contract a barista (https://github.com/tidyverse/tidy-dev-day/issues/34) — @DavisVaughan 
    * Find a barista, possibly https://www.livewire.coffee/
    * Construct a 1 day contract, 1 barista for ~100 people seems to be fine, ~$2000 or less. Optionally, add a custom menu with R specific coffee drink names (this was a big hit as posit conf)
    * Ensure the barista has enough space and access to an outlet

## One month before (August)

* [x] Order food (for 2024, see #38) — @hfrick 
    * [ ] Ensure they have an American phone number / someone there in person
    * [ ] Consider buying the coffee baristas lunch, they really appreciated it
* [x] Host an online Git workshop — @mine-cetinkaya-rundel 
* [x] Package upkeep (https://github.com/tidyverse/tidy-dev-day/issues/46) — @gaborcsardi 
* [x] Plan issue labelling extravaganza. Tracking in #79. — @jennybc 
    * [ ] Review really old issues with the label. Are they still relevant? With this link https://github.com/search?q=org%3Atidyverse%20label%3A%22tidy-dev-day%20%3Anerd_face%3A%22%20&type=issues
* [x] Plan social time + post-TDD destination — @hadley (https://maxlagers.com/host-events/ ?)

## One week before

* [x] Adhesive sommelier makes labels (https://github.com/tidyverse/tidy-dev-day/issues/35) — @thomasp85 
* [x] Buy snacks (https://github.com/tidyverse/tidy-dev-day/issues/40). ~$250. — @DavisVaughan
    * [x] Napkins
    * [x] Plates
    * [x] Cups
    * [x] Utensils (if doing something more complex than sandwiches)
    * [x] Beverages (sparking water, sodas)
    * [x] Chips
    * [x] Using DoorDash works well if you are short on time / cars. You can even order a rolling cooler for ice this way. 
* [x] Buy nametags and sharpies
* [x] Buy tape for labels, because label adhesive is never strong enough
* [x] Polish (and print) ice breaker activity (bingo was great!) — @simonpcouch 
* [x] Polish (and print) PR worksheet — @EmilHvitfeldt 
* [x] Polish opening and closing slides — @hadley

## Day of

* [x] Transporter of the Gong (x2) — 
    * [x] Make sure you have tape for the Gong return box
* [x] Buy ice
* [x] Photographer — @georgestagg 
* [ ] Welcomer (https://github.com/tidyverse/tidy-dev-day/issues/50) — @simonpcouch 

## Afterwards

* [ ] Write a round up blog post — @topepo

**Comment by jennybc** [comment]
Re: catering survey: make this more constrained than a free text box.

**Comment by hadley** [comment]
If it's not clear what you're doing, please make a PR to the README that describes it.

**Comment by topepo** [comment]
blog post PR: tidyverse/tidyverse.org#742

[preview](https://deploy-preview-742--tidyverse-org.netlify.app/blog/2025/06/tdd-2025/) with several TODOs to fill in the details.

**Comment by hfrick** [comment]
A heads-up: unfortunately, we don't have fridge access at the new venue 

> We don’t have a fridge available.  We’re happy to provide beverages with a beverage package but our back of house areas are not available to access to guests, clients, or outside vendors.

**Comment by lionel-** [comment]
Keep in touch 6 weeks and 2 weeks before event with venue to make sure they're still good for it (at tdd-2025 our venue cancelled 1 week before the event)

**Comment by hfrick** [comment]
Lunch order: next year with a contact who is there in person

**Comment by DavisVaughan** [comment]
Only provide 1 drink ticket per person, expect that some people drop out by the end of the day so some people can get 2 if they want, but we don't need to order >1 per person.

The key is to tell a bar it is a "public event" with 80 people, that seems to help avoid them thinking we need a private room with a minimum fee and required food ordering
